# Generated by Django 3.2.5 on 2021-07-25 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=8)),
                ('contacto', models.CharField(max_length=11)),
                ('correo', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('anios_experiencia', models.IntegerField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=30, null=True)),
                ('alfabetizacion_digital', models.CharField(blank=True, max_length=30, null=True)),
                ('activos_tecnológicos', models.IntegerField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_hijos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agricultor',
                'verbose_name_plural': 'Agricultores',
                'db_table': 'AGRICULTOR',
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('conciencia', models.CharField(blank=True, max_length=200, null=True)),
                ('integridad', models.CharField(blank=True, max_length=200, null=True)),
                ('habilidad_cognitiva', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'COMUNIDAD',
            },
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('prevision_produccion', models.CharField(max_length=200)),
                ('deuda', models.FloatField()),
                ('costo_mano_obra', models.FloatField()),
                ('gastos_agua_riego', models.FloatField()),
                ('costo_total', models.FloatField()),
                ('precio_medio_venta', models.FloatField()),
                ('ingresos_otros_cultivos', models.FloatField(blank=True, null=True)),
                ('ingresos_no_agrícolas', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Finanzas',
                'verbose_name_plural': 'Finanzas',
                'db_table': 'FINANZAS',
            },
        ),
        migrations.CreateModel(
            name='Tierra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('geolocalizacion', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('area_campo', models.IntegerField()),
                ('cultivo', models.CharField(blank=True, max_length=200, null=True)),
                ('edad_cultivo', models.IntegerField(blank=True, null=True)),
                ('tipo_suelo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_riego', models.CharField(blank=True, max_length=200, null=True)),
                ('frecuencia_riego', models.CharField(blank=True, max_length=200, null=True)),
                ('historial_medio_rendimiento', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tierra',
                'verbose_name_plural': 'Tierras',
                'db_table': 'TIERRA',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('informacion', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('agricultor', models.ForeignKey(db_column='agricultor', on_delete=django.db.models.deletion.PROTECT, related_name='agricultor', to='Pacha.agricultor', verbose_name='Agricultor')),
                ('geolocalizacion', models.ForeignKey(db_column='tierra', on_delete=django.db.models.deletion.PROTECT, related_name='tierra', to='Pacha.tierra', verbose_name='Tierra')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'db_table': 'CULTIVO',
            },
        ),
    ]
